# Use a base image with JDK
FROM rohit2127/open-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file into the container
COPY patient-service-0.0.1-SNAPSHOT.jar /app/patient-service.jar

# Start the application
CMD ["java", "-jar", "/app/patient-service.jar"]